# Generated by Django 4.2 on 2023-07-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('slot_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_key', models.CharField(max_length=100)),
                ('crn', models.CharField(max_length=10, unique=True)),
                ('course_identification', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=4)),
                ('course_number', models.CharField(max_length=6)),
                ('section', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('meeting_times', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(0, 'Single meeting time'), (1, 'Special Course'), (2, 'Multiple meeting times'), (3, 'No exams')], default=2, max_length=30)),
                ('verified', models.BooleanField(default=False)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='optimizer.coursegroup')),
            ],
        ),
    ]
