# Generated by Django 4.2 on 2023-07-07 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='optimizer.coursegroup'),
        ),
    ]
