# Generated by Django 4.2 on 2023-07-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_alter_course_course_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='slot_id',
            field=models.IntegerField(default=-1),
        ),
    ]
