# Generated by Django 4.2 on 2023-07-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0003_alter_coursegroup_slot_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='verified',
            new_name='clear',
        ),
    ]
