# Generated by Django 4.2 on 2023-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0004_rename_verified_course_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
