# Generated by Django 4.2 on 2023-07-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0005_coursegroup_is_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
