# Generated by Django 4.2 on 2023-09-04 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0006_dbprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_start_date', models.DateField()),
                ('exam_end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester_key',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='is_special',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='semester_key',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='slot_id',
        ),
        migrations.AddField(
            model_name='course',
            name='crosslisted',
            field=models.ManyToManyField(to='optimizer.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[(0, 'Single meeting time'), (1, 'Special Course'), (2, 'Multiple meeting times')], default=2, max_length=30),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('enrolled_courses', models.ManyToManyField(to='optimizer.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='optimizer.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('students_overlap', models.IntegerField(default=0)),
                ('students_3in24', models.IntegerField(default=0)),
                ('students_4in48', models.IntegerField(default=0)),
                ('students_b2b', models.IntegerField(default=0)),
                ('students_night_morning', models.IntegerField(default=0)),
                ('faculty_overlap', models.IntegerField(default=0)),
                ('faculty_b2b', models.IntegerField(default=0)),
                ('is_updated', models.BooleanField(default=False)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='optimizer.semester')),
            ],
        ),
        migrations.CreateModel(
            name='CourseGroupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField(default=-1)),
                ('has_exam', models.BooleanField(default=True)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='optimizer.coursegroup')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='optimizer.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='optimizer.semester'),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='optimizer.semester'),
        ),
    ]
