# Generated by Django 4.2 on 2023-09-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0007_semester_remove_course_semester_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[(9, 'No meeting time'), (0, 'Single meeting time'), (1, 'Special Course'), (2, 'Multiple meeting times')], default=2, max_length=30),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
