# Generated by Django 4.2 on 2023-09-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0008_coursegroup_is_special_alter_course_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='students_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
