# Generated by Django 4.2 on 2023-10-16 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0009_semester_students_file_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_duplicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[(0, 'The schedule is successfully created.'), (1, 'The schedule is analyzed.'), (2, 'Analyzing the schedule...'), (10, 'Step 1/3 Creating the IP model for schedule generation...'), (11, 'Step 2/3 Initial optimization...'), (12, 'Step 3/3 Final optimization...'), (13, 'Analyzing the schedule...'), (99, 'ERROR. Delete and try again.')], default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
