# Generated by Django 4.2 on 2023-10-29 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0010_schedule_is_duplicated_schedule_original_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='is_updated',
            new_name='analyzed',
        ),
    ]
