# Generated by Django 4.2 on 2023-10-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0011_rename_is_updated_schedule_analyzed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='crn',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[(0, 'The schedule is successfully created.'), (1, 'The schedule is analyzed.'), (2, 'Analyzing the schedule...'), (3, "The schedule is updated and hasn't being analyzed yet."), (10, 'Step 1/3 Creating the IP model for schedule generation...'), (11, 'Step 2/3 Initial optimization...'), (12, 'Step 3/3 Final optimization...'), (13, 'Analyzing the schedule...'), (99, 'ERROR. Delete and try again.')], default=0, max_length=5),
        ),
    ]
