# Generated by Django 5.0.6 on 2024-05-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0012_alter_course_crn_alter_schedule_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('overlap', models.FloatField(default=1)),
                ('threein24', models.FloatField(default=0.1)),
                ('fourin48', models.FloatField(default=0.2)),
                ('backtoback', models.FloatField(default=0.02)),
                ('nighttomorning', models.FloatField(default=0.04)),
                ('night', models.FloatField(default=0)),
                ('facultyoverlap', models.FloatField(default=0.2)),
                ('facultybacktoback', models.FloatField(default=0.05)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.schedule'),
        ),
    ]
