# Generated by Django 5.0.6 on 2024-05-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0013_preferenceprofile_alter_schedule_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='student_overlap_problems',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
