# Generated by Django 5.0.6 on 2024-05-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0013_preferenceprofile_alter_schedule_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group2slot', models.JSONField()),
                ('students_overlap', models.IntegerField(default=0)),
                ('students_3in24', models.IntegerField(default=0)),
                ('students_4in48', models.IntegerField(default=0)),
                ('students_b2b', models.IntegerField(default=0)),
                ('students_night_morning', models.IntegerField(default=0)),
                ('faculty_overlap', models.IntegerField(default=0)),
                ('faculty_b2b', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.schedule')),
            ],
        ),
    ]
