# Generated by Django 5.0.6 on 2024-05-29 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0014_scheduleversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='current_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_version', to='optimizer.scheduleversion'),
        ),
        migrations.AlterField(
            model_name='scheduleversion',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='optimizer.schedule'),
        ),
    ]
