# Generated by Django 5.0.6 on 2024-05-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0014_schedule_student_overlap_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='faculty_b2b_problems',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='faculty_overlap_problems',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='student_3in24_problems',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='student_4in48_problems',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='student_b2b_problems',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='student_night_morning_problems',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
