# Generated by Django 5.0.6 on 2024-05-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0015_schedule_faculty_b2b_problems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='exam_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='num_exams_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semester',
            name='time_between_exams',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
