# Generated by Django 5.0.6 on 2024-06-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0015_schedule_current_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleversion',
            name='name',
            field=models.TextField(default='New Version', max_length=50),
        ),
    ]
