# Generated by Django 5.0.6 on 2024-06-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0016_semester_exam_start_time_semester_num_exams_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='exam_start_time',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='num_exams_per_day',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='time_between_exams',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.coursegroup'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.semester'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.semester'),
        ),
        migrations.AlterField(
            model_name='coursegroupschedule',
            name='course_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.coursegroup'),
        ),
        migrations.AlterField(
            model_name='coursegroupschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optimizer.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.semester'),
        ),
    ]
