# Generated by Django 5.0.6 on 2024-06-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0017_remove_semester_exam_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='exam_start_times',
            field=models.CharField(default='8:00 AM, 11:45 AM, 3:30 PM, 7:30 PM', max_length=150),
        ),
    ]
