# Generated by Django 5.0.6 on 2024-06-04 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0019_alter_course_course_group_alter_course_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.coursegroup'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.semester'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.semester'),
        ),
        migrations.AlterField(
            model_name='coursegroupschedule',
            name='course_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.coursegroup'),
        ),
        migrations.AlterField(
            model_name='coursegroupschedule',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='optimizer.semester'),
        ),
    ]
