# Generated by Django 5.0.6 on 2024-06-04 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0020_alter_course_course_group_alter_course_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='optimizer.semester'),
        ),
    ]
