# Generated by Django 5.0.6 on 2024-06-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0021_alter_schedule_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='optimizer.schedule'),
        ),
    ]
