# Generated by Django 5.0.6 on 2024-06-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0016_scheduleversion_name'),
        ('optimizer', '0022_alter_schedule_original'),
    ]

    operations = [
    ]
