# Generated by Django 5.0.6 on 2024-06-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0023_merge_20240611_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleversion',
            name='faculty_b2b_problems',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='faculty_overlap_problems',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='student_3in24_problems',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='student_4in48_problems',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='student_b2b_problems',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='student_night_morning_problems',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='student_overlap_problems',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
