# Generated by Django 5.0.6 on 2024-06-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0024_scheduleversion_faculty_b2b_problems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='crosslisted',
        ),
    ]
