# Generated by Django 5.0.6 on 2024-06-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0025_remove_course_crosslisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='student_forced_overlap',
            field=models.IntegerField(default=0),
        ),
    ]
