# Generated by Django 5.0.6 on 2024-06-27 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0026_schedule_student_forced_overlap'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='academic_period',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='semester',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
