# Generated by Django 5.0.6 on 2024-07-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0027_semester_academic_period_semester_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.coursegroup'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.semester'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.semester'),
        ),
        migrations.AlterField(
            model_name='coursegroupschedule',
            name='course_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.coursegroup'),
        ),
        migrations.AlterField(
            model_name='coursegroupschedule',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.semester'),
        ),
    ]
