# Generated by Django 5.0.6 on 2024-07-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0027_semester_academic_period_semester_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='preference_profile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
