# Generated by Django 5.0.6 on 2024-07-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0028_schedule_preference_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='group_constraints',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='predefined_constraints',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
