# Generated by Django 5.0.6 on 2024-07-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0029_schedule_group_constraints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='group_constraints',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='predefined_constraints',
        ),
    ]
