# Generated by Django 5.0.6 on 2024-07-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0030_remove_schedule_group_constraints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='group_constraints',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='predefined_constraints',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
