# Generated by Django 5.0.6 on 2024-07-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0028_alter_course_course_group_alter_course_semester_and_more'),
        ('optimizer', '0031_schedule_group_constraints_and_more'),
    ]

    operations = [
    ]
