# Generated by Django 5.0.6 on 2024-07-11 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0032_merge_20240708_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='suite_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='semester',
            name='special_courses',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='optimizer.semester'),
        ),
    ]
 