# Generated by Django 5.0.6 on 2024-07-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0033_schedule_suite_id_semester_special_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='suite_id',
            new_name='portfolio_id',
        ),
    ]
