# Generated by Django 5.0.6 on 2024-07-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0034_portfolioid_rename_suite_id_schedule_portfolio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='special_courses',
        ),
    ]
