# Generated by Django 5.0.6 on 2024-07-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0035_remove_semester_special_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='special_courses',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
