# Generated by Django 5.0.6 on 2024-07-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0036_semester_special_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='special_courses',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
