# Generated by Django 5.0.6 on 2024-09-02 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0037_alter_semester_special_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroupschedule',
            name='course_group',
        ),
        migrations.AddField(
            model_name='coursegroupschedule',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursegroupschedule',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='course_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.schedule'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optimizer.semester'),
        ),
    ]
