# Generated by Django 5.0.6 on 2024-11-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0038_remove_coursegroupschedule_course_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='inconvenient_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='inconvenient_students_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
