# Generated by Django 5.0.6 on 2024-11-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0039_schedule_inconvenient_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleversion',
            name='inconvenient_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='inconvenient_students_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
