# Generated by Django 5.0.6 on 2025-07-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0040_scheduleversion_inconvenient_students_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DBProgress',
        ),
    ]
